### ISSUE TITLE
Use of String.to_atom makes DoS possible

### ISSUE THREAD

**Issue by Nicd** [bluzky/querie#1]
The project uses `String.to_atom/1` in several places, for example here: https://github.com/bluzky/querie/blob/ae5a297161855c0194cbd432581055de119d61bc/lib/parser.ex#L49-L59

Using `String.to_atom/1` on dynamic or user-provided input opens the possibility for denial of service attacks. The issue stems from the fact that the BEAM atom table has a fixed maximum size. If this size is exceeded, the whole VM crashes. When a user provides strings that are converted to atoms, they an easily overflow the atom table.

The alternative is to use `String.to_existing_atom/1`, which will only support atoms that already exist in the atom table (i.e. have been already used in the code). Or the code needs to be structured to use e.g. strings instead of atoms.

**Comment by bluzky** [comment]
Thanks for your feedback.
I almost forgot that
